package viki

// Code generated by gen-assets.sh; DO NOT EDIT.

import (
	_ "embed"
	"html/template"
)

var (
	//go:embed static/external-link.png
	static_external_link_png []byte

	//go:embed static/favicon/favicon-16x16.png
	static_favicon_favicon_16x16_png []byte

	//go:embed static/favicon/favicon-32x32.png
	static_favicon_favicon_32x32_png []byte

	//go:embed static/favicon/favicon.ico
	static_favicon_favicon_ico []byte
)

var staticAssetFileMap = map[string][]byte{
	"_viki_static/external-link.png":         static_external_link_png,
	"_viki_static/favicon/favicon-16x16.png": static_favicon_favicon_16x16_png,
	"_viki_static/favicon/favicon-32x32.png": static_favicon_favicon_32x32_png,
	"_viki_static/favicon/favicon.ico":       static_favicon_favicon_ico,
}

var (
	//go:embed templates/base/page.gohtml
	raw_base_page_gohtml      string
	template_base_page_gohtml = template.Must(template.New("page").Parse(raw_base_page_gohtml))

	//go:embed templates/base/sidebar.gohtml
	raw_base_sidebar_gohtml      string
	template_base_sidebar_gohtml = template.Must(template.New("sidebar").Parse(raw_base_sidebar_gohtml))

	//go:embed templates/base/theme.css.tpl
	raw_base_theme_css_tpl      string
	template_base_theme_css_tpl = template.Must(template.New("theme").Parse(raw_base_theme_css_tpl))
)
