package viki

// Code generated by gen-assets.sh; DO NOT EDIT.

import _ "embed"

var (
	//go:embed static/external-link.png
	static_external_link_png []byte

	//go:embed static/favicon/favicon-16x16.png
	static_favicon_favicon_16x16_png []byte

	//go:embed static/favicon/favicon-32x32.png
	static_favicon_favicon_32x32_png []byte

	//go:embed static/favicon/favicon.ico
	static_favicon_favicon_ico []byte
)

var staticAssetFileMap = map[string][]byte{
	"_viki_static/external-link.png":         static_external_link_png,
	"_viki_static/favicon/favicon-16x16.png": static_favicon_favicon_16x16_png,
	"_viki_static/favicon/favicon-32x32.png": static_favicon_favicon_32x32_png,
	"_viki_static/favicon/favicon.ico":       static_favicon_favicon_ico,
}
