#!/usr/bin/sh

# Generates assets.go, which has all assets embedded in vars

# Find all files in the static directory
files=$(find ./static -type f)

function filenameToVar() {
    echo "${1#./static/}" | sed 's/[^a-zA-Z0-9]/_/g' | sed 's/^_//'
}

# Start the assets.go file
echo 'package viki' > assets.go
echo '' >> assets.go
echo '// Code generated by gen-assets.sh; DO NOT EDIT.' >> assets.go
echo '' >> assets.go
echo 'import _ "embed"' >> assets.go
echo '' >> assets.go
echo 'var (' >> assets.go

# Loop through each file and embed its content
for file in $files; do
    var_name=$(filenameToVar "${file}")
    echo "	//go:embed ${file#./}" >> assets.go
    echo "	static_${var_name} []byte" >> assets.go
    echo '' >> assets.go
done

echo ")" >> assets.go

# Create a map of the filenames to the variables
echo '' >> assets.go
echo 'var staticAssetFileMap = map[string][]byte{' >> assets.go
for file in $files; do
    var_name=$(filenameToVar "${file}")
    echo "	\"_viki_static/${file#./static/}\": static_${var_name}," >> assets.go
done
echo '}' >> assets.go

# Quietly fix up our whitespace abuse
go fmt assets.go > /dev/null 2>&1