name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Run tests
        run: |
          # Can't seem to get the executable flag to stick from windows, remove once it's fixed
          chmod +x ./lib/viki/gen-assets.sh
          make test